auth0:
  audience: https://dev-hfm58bxg2683jzf2.us.auth0.com/api/v2/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-hfm58bxg2683jzf2.us.auth0.com/